### ISSUE TITLE
Report help tag often covers Magnet icon

### ISSUE THREAD

**Issue by ChaosOrdeal** [just5ky/torrents-csv#16]
This is a suggestion regarding the website torrents-csv.ml (which may not be your website, in which case please close and disregard)

After each torrent, there is a short string of icons.  Many times I have attempted to click the magnet (u-shaped) only to have the "Report" help text from the report link pop out and cover up the magnet icon, so when I click, I go to the report page, rather than downloading the magnet information.

Possible fixes:
suppress the pop-up help text
move the pop-up up or down
move the icons further apart so that the pop-up text does not cover its neighbor

Not a huge issue, but it's probably a very quick fix.

**Comment by just5ky** [comment]
I'm not the original developer.
This repo is a fork to support arm64 docker images

Here's the original repo, you can post your queries there
https://gitea.com/heretic/torrents-csv-server

**Comment by ChaosOrdeal** [comment]
Thanks for the heads up.
